tap "adoptopenjdk/openjdk"
tap "github/gh"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"

brew "docker", link: false
brew "docker-compose", link: false
brew "fish"
brew "fzf"
brew "gawk"
brew "gh"
brew "ghq"
brew "git"
brew "gron"
brew "hey"
brew "nkf"
brew "node"
brew "parallel"
brew "sd"
brew "telnet"
brew "tig"
brew "tmux-xpanes"
brew "vim"
brew "chezmoi"

cask "adoptopenjdk11"
cask "alfred"
cask "microsoft-edge"
cask "microsoft-remote-desktop-beta"
cask "rectangle"
cask "stoplight-studio"
cask "toggl"
cask "tunnelblick"
