#!/bin/bash

brew bundle --no-lock --file=/dev/stdin <<EOF
tap "adoptopenjdk/openjdk"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "versent/taps"

brew "awscli"
brew "coreutils"
brew "asdf"
brew "bash"
brew "bat"
brew "chezmoi"
brew "curl"
brew "fd"
brew "python@3.9"
brew "direnv"
brew "docker"
brew "docker-compose"
brew "diff-so-fancy"
brew "fish"
brew "fzf"
brew "gawk"
brew "gcc"
brew "gh"
brew "ghq"
brew "git"
brew "git-secrets"
brew "gron"
brew "hey"
brew "howdoi"
brew "jq"
brew "navi"
brew "nkf"
brew "parallel"
brew "ripgrep"
brew "saml2aws"
brew "sd"
brew "telnet"
brew "terminal-notifier"
brew "tig"
brew "tmux"
brew "tmux-xpanes"
brew "up"
brew "wget"
brew "neovim"

cask "adoptopenjdk11"
cask "alfred"
cask "alt-tab"
cask "discord"
cask "google-japanese-ime"
cask "amazon-workspaces"
cask "aws-vault"
cask "docker"
cask "hiddenbar"
cask "intellij-idea"
cask "iterm2"
cask "itsycal"
cask "jdk-mission-control"
cask "karabiner-elements"
cask "maccy"
cask "microsoft-edge"
cask "onyx"
cask "rectangle"
cask "session-manager-plugin"
cask "skitch"
cask "slack"
cask "stats"
cask "stoplight-studio"
EOF

exit 0
