#!/usr/bin/env sh

# global settings
yabai -m config auto_balance                 on

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  08
yabai -m config bottom_padding               08
yabai -m config left_padding                 08
yabai -m config right_padding                08
yabai -m config window_gap                   08
