#!/usr/bin/env sh

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  14
yabai -m config bottom_padding               14
yabai -m config left_padding                 14
yabai -m config right_padding                14
yabai -m config window_gap                   14

# global settings
yabai -m config mouse_follows_focus          on
borders &
