#!/usr/bin/env sh

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  08
yabai -m config bottom_padding               08
yabai -m config left_padding                 08
yabai -m config right_padding                08
yabai -m config window_gap                   06

# global settings
yabai -m config mouse_follows_focus          on
borders active_color=0xff1122ff inactive_color=0xffffffff width=6 &
