name: CI

on: [push]

jobs:
  install-dotfiles:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11.0]
    steps:
      - uses: actions/checkout@v1
      - name: Install required packages
        run: brew install bash
      - name: Install dotfiles
        run: /bin/bash -x bootstrap.sh

