name: CI

on: [push]

jobs:
  install-dotfiles:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11.0, ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Install required packages
        run: brew install git curl bash
      - name: Install dotfiles
        run: /bin/bash -x executable_bootstrap.sh

