name: CI

on: [push]

jobs:
  install-dotfiles-on-mac:
    runs-on: ${{ matrix.os_version }}
    strategy:
      matrix:
        os_version: [macos-10.15, macos-11.0]
    steps:
      - uses: actions/checkout@v1
      - name: Install required packages
        run: brew install bash
      - name: Install dotfiles
        run: /bin/bash -xc "$(curl -fsSL https://raw.githubusercontent.com/nakahararuu/dotfiles/master/executable_bootstrap.sh)"

  install-dotfiles-on-ubuntu:
    runs-on: ubuntu-latest
    needs: install-dotfiles-on-mac
    steps:
      - uses: actions/checkout@v1
      - name: Install required packages
        run: brew install git curl bash
      - name: Install dotfiles
        run: /bin/bash -xc "$(curl -fsSL https://raw.githubusercontent.com/nakahararuu/dotfiles/master/executable_bootstrap.sh)"

